### ISSUE TITLE
Forgotten unicode.h ?

### ISSUE THREAD

**Issue by dmikushin** [Mozer/talk-llama-fast#12]
Upon building from source, I'm getting the following error:

```
CMake Error at CMakeLists.txt:88 (add_library):
  Cannot find source file:

    unicode.h
```

Looks like the `unicode.h` file was not added into the repo, could you please check?

**Comment by Mozer** [comment]
There's no need for `unicode.h`  for talk-llama (not used).
What module has this CMakeLists.txt? There several of those files.
I didn't change other files, just those for talk-llama.cpp.  What OS are you using? I just tried building everything again and it was ok in Win11.

**Comment by Mozer** [comment]
HISTORY: I forked newer version of whisper and then uploaded some local files from my older forked version, so there were lots of errors.

Now I synced this repo. It is now a bit older version from 14.02.2024, but it is compiling well. Sometime in future i will sync to current upstream version of whisper if there are important changes.

**Comment by dmikushin** [comment]
As we figured out, the @Mozer 's changeset must be applied to the correct commit of origin. It's done in #16 , and the problem is resolved.
