### ISSUE TITLE
Where can I get        talk-llama-wav2lip.bat or talk-llama-wav2lip-ru.bat or talk-llama-just-audio.bat?

### ISSUE THREAD

**Issue by golegus** [Mozer/talk-llama-fast#13]

**Comment by Mozer** [comment]
in Releases section. https://github.com/Mozer/talk-llama-fast/releases/tag/0.1.3
download [talk-llama-fast-v0.1.3.zip](https://github.com/Mozer/talk-llama-fast/releases/download/0.1.3/talk-llama-fast-v0.1.3.zip)

**Comment by golegus** [comment]
Thanks!
