### ISSUE TITLE
Failed building wheel for TTS

### ISSUE THREAD

**Issue by Vander1nde21** [Mozer/talk-llama-fast#21]
Hi,
Doing a clean installation of talk-llama-fast. I ran pip install git+https://github.com/Mozer/tts but the results i get is this.

  C:\Users\\miniconda3\envs\xtts\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TTS
Failed to build TTS
ERROR: Could not build wheels for TTS, which is required to install pyproject.toml-based projects

I've installed visual studio build tools. Here is what i've selected

![image](https://github.com/Mozer/talk-llama-fast/assets/78788365/6e2ae78d-ed22-4a3e-8421-f06c092352ad)

![image](https://github.com/Mozer/talk-llama-fast/assets/78788365/4c91f49b-ae89-4315-8e14-645d877cb511)

**Comment by Mozer** [comment]
Take a look here:
https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory
maybe this will help:

You need windows 10 SDK, Download [visual studio build tools](https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019) and install

Visual C++ Build tools core features.
MSVC toolset C++ 2019 v142 (x86,x64)
Visual C++ 2019 Redistributable Update
Windows 10 SDK (10.0.17763.0) for Desktop C++

**Comment by Vander1nde21** [comment]
Did all steps, strangely enough, nothing changed. Also Windows 10 SDK (10.0.17763.0) for Desktop C++ didn't exist, or doesn't exist anymore so I chose another windows 10 SDK version option that I could only select and that didn't work as well. I even tried reinstalling build tools 2022. still nothing.
