### ISSUE TITLE
Срочно помощь нужна! Ошибка invalid literal for int() with base 10: '\x00'

### ISSUE THREAD

**Issue by denny4-user** [Mozer/talk-llama-fast#26]
![cmd_DupfxfZVqM](https://github.com/Mozer/talk-llama-fast/assets/82503296/317fe68a-b6fd-4b87-b40d-2cb02b820227)
как то странно получилось. В самый первый раз как ставил ИИ - было всё норм, потом решил переустоновить в другое место и вот такая ошибка, сделал ВСЁ по инструкции (даже несколько раз).

**Comment by Mozer** [comment]
Ничего страшного. Запусти и поговори с talk-llama-fast, она перезапишет файл xtts_play_allowed.txt. Видимо, у тебя он пустой почему-то оказался.

**Comment by Mozer** [comment]
Попробуй удалить этот файл и заново запустить ламу и спросить у нее что-то

**Comment by denny4-user** [comment]
ООО, не, я исправил, у меня файлик валялся просто в: C:\TEMP. Спасибо большое!
