### ISSUE TITLE
talk-llama.exe вылетает

### ISSUE THREAD

**Issue by Const366** [Mozer/talk-llama-fast#27]
Добрый день!

При запуске talk-llama-audio-ru.bat, talk-llama.exe вылетает как показано в приложении, в чем может быть проблема?

Geforce 4060 16Gb,  cuda toolkit и последние драйвера установлены.

Заранее  спасибо за ответ,
С уважением, Конст
![github](https://github.com/Mozer/talk-llama-fast/assets/169592853/d4ae5e55-62e8-48a3-83cd-468033f8bd58)

**Comment by Mozer** [comment]
4060 ti?
Попробуйте с параметром -ngl 0.

**Comment by Const366** [comment]
Попробовал с -ngl 0, результат тот-же -падает. Кстати, при запуске английской версии работает чуть дольше (экран в приложении).

RTX 4060ti 16G VRAM, Intel i5-2500K, 16G RAM, Win 10.
![Безымянный-2](https://github.com/Mozer/talk-llama-fast/assets/169592853/9fd36a98-a188-44ad-b27a-2987326e60e3)

**Comment by Mozer** [comment]
Процессор i5-2500K не поддерживает инструкции AVX2. Надо перекомпилировать talk-llama-fast без поддержки avx. Тут есть детали: https://github.com/ggerganov/whisper.cpp/issues/1939

**Comment by Const366** [comment]
Спасибо!
Буду менять CPU, давно пора....

**Comment by Mozer** [comment]
[talk-llama-fast-v0.1.7_noavx2.zip](https://github.com/Mozer/talk-llama-fast/files/15355663/talk-llama-fast-v0.1.7_noavx2.zip)
Скомпилировал talk-llama-fast с параметром `-DWHISPER_NO_AVX2 1`
Если запустится у вас - выложу в релизы.

**Comment by Const366** [comment]
Отлично! Все загрузилось, Спасибо Огромное!!!
