### ISSUE TITLE
Входящий текст по API или ещё как-либо

### ISSUE THREAD

**Issue by Gourieff** [Mozer/talk-llama-fast#33]
Приветствую!
Огромное спасибо за такую реализацию, всё отлично работает (кроме момента с аудио вводом сообщения: когда llama слушает аудио, нет от неё видео - выставляю --vad-start-thold на 0 видео соответствнно появляется, но тогда нет аудио ввода - но это не суть :)
Возник другой вопрос, есть ли сейчас какой-то во всём этом функционал, чтобы запрос от пользователя попадал в модуль talk-llama не через ввод текста в диалоговом окне (или аудио), а, например, через API или, может, командную строку или ещё как-то (подхват, например, из текстового файла)
Делаю ТГ-бота, вывод видео-сообщений сделал, но пока не могу понять, как скормить в запущенный модуль talk-llama входящий промпт от пользователя

**Comment by Mozer** [comment]
Используется API от xtts-API-sever:

std::string data = "{\"text\":\""+text+"\", \"language\":\""+language+"\", \"speaker_wav\":\""+speaker_wav+"\", \"reply_part\":\""+std::to_string(reply_part)+"\"}";

Апи от xtts сам отправляет запрос в апи silly extras в wav2lip.
Но в текущей реализации финальное видео сразу воспроизводится, без сохранения на диск. 
Вам нужно будет подредактировать обработку в wav2lip, чтобы он сохранял и отдавала вам видео.

**Comment by Gourieff** [comment]
Благодарю за наводку, потестировал через постман, конструкция `{"text":""+text+"", "language":""+language+"", "speaker_wav":""+speaker_wav+"", "reply_part":""+std::to_string(reply_part)+""}"` работает отлично, но это, получается, что персонаж просто проговаривает то, что я отправил в text 🤔 А как именно отправить ввод от пользователя, именно сам входящий запрос, который в консоли talk-llama.exe пользователь пишет? Т.е. идея в том, что примерно как у вас реализовано в ТГ чате с персонажами, только у меня планируется один персонаж и именно как бот - т.е. пользователь пишет вопрос, и персонаж отвечает видеосообщением в боте.
> Вам нужно будет подредактировать обработку в wav2lip, чтобы он сохранял и отдавала вам видео

Вот этот момент я сделал, видео ответов сохраняются в отдельную папку, но пока не совсем понял, есть ли такое, чтобы llama.cpp "слушал" вопросы пользователя не только через ввод непосредственно в консоли talk-llama.exe

**Comment by Gourieff** [comment]
> Используется API от xtts-API-sever:
> 
> std::string data = "{"text":""+text+"", "language":""+language+"", "speaker_wav":""+speaker_wav+"", "reply_part":""+std::to_string(reply_part)+""}";
> 
> Апи от xtts сам отправляет запрос в апи silly extras в wav2lip. Но в текущей реализации финальное видео сразу воспроизводится, без сохранения на диск. Вам нужно будет подредактировать обработку в wav2lip, чтобы он сохранял и отдавала вам видео.

Всё, наконец-то дошло до меня... Огромное спасибо, это по сути ведь то, что надо 😎 🤝
Сразу не понял, как это можно обыграть в рамках задачи
