### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by cerulliber** [Mozer/talk-llama-fast#34]
1.so It won't work on gt 730 + ryzen 3600 16gb ram ?
 Device 0: GeForce GT 730, compute capability 3.5, VMM: yes
llm_load_tensors: ggml ctx size =    0.27 MiB
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 4679.55 MiB on device 0: cudaMalloc failed: out of memory
llama_model_load: error loading model: unable to allocate backend buffer
llama_load_model_from_file: failed to load model
llama_new_context_with_model: model cannot be NULL

----
2. also clicked talk-llama.exe by mistake. do I need to restart install?

thank you so much!

**Comment by Mozer** [comment]
Not sure if  gt 730 is supported. But you can try to change params in bat: `-ngl 0` (0 layers to GPU) or  `-ng` (no GPU)
